services:
  data_recorder:
    container_name: data_recorder
    image: data_recorder
    build: 
      context: ../../../
      dockerfile: ./DT-solution/DTservices/data_recorder/Dockerfile
    networks:
      - shared-communication

networks:
  shared-communication:
    external: true