services:
  influxdb:
    container_name: influxdb-server
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ur3e
      DOCKER_INFLUXDB_INIT_PASSWORD: ur3eur3e
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: mybucket
    volumes:
      - db-data:/var/lib/influxdb:rw
    ports:
      - 8086:8086
    networks:
      - shared-communication
  grafana:
    image: grafana/grafana:10.3.3
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana-data:/var/lib/grafana
  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3.12-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ur3e
      RABBITMQ_DEFAULT_PASS: ur3e
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    networks:
      - shared-communication
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp &&
            docker-entrypoint.sh rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 15s
  mockup:
    container_name: ur3e_mockup
    build:
      context: ./ur3e_mockup
      dockerfile: ${DOCKERFILE:-Dockerfile.x86}
    volumes:
      - ./startup/startup.conf:/app/startup.conf:z
    networks:
      - shared-communication
    restart: unless-stopped
    depends_on:
      - rabbitmq
  data_recorder:
    container_name: data_recorder
    build: 
      context: .
      dockerfile: DTsolution/DTservices/data_recorder/Dockerfile
  rt_robot_prediction:
    container_name: robot_prediction
    build: 
      context: .
      dockerfile: DTsolution/DTservices/RT_robot_prediction/Dockerfile
    



networks:
  shared-communication:

volumes:
  db-data:
  grafana-data: