rabbitmq: {
    ip       = "localhost"
    port     = 5672
    username = ur3e
    password = ur3e
    exchange = UR3E_AMQP
    type     = topic
    vhost    = /
}

influxdb: {
    url = http://127.0.0.1:8086
    token = "Bh-BBOJD_git0KspbOz9_Ut7RY5S1EU6dhoJlEw7tlN-8S_MFsX7yuam7l1WFI-i-5iFGejn-fYflUHbQvrdwA=="
    org = robotarm
    bucket = robotarm
}

physical_twin: {
    pt_mockup: {
        initial_q         = [0.0, -1.57, 1.57, -1.57, -1.57, 0.0]
        speedup           = 1
        publish_frequency = 20
        max_velocity      = 60  # degrees per second
        acceleration      = 80  # degrees per second squared
    }
}

digital_twin: {
    robot_model: {
        initial_q         = [0.0, -1.57, 1.57, -1.57, -1.57, 0.0]
        time_step         = 0.01
        publish_period    = 0.05
        max_velocity      = 1.0472 #60 deg
        acceleration      = 1.39626 #80 deg
    }
}


