services:
  influxdb:
    container_name: influxdb-server
    image: influxdb
    build: ./
    volumes:
      - ./data/:/var/lib/influxdb:rw # Read write access to data collected
    ports:
      - 8086:8086
    networks:
      - shared-communication

networks:
  shared-communication:
    external: true