services:
  RT_robot_prediction:
    container_name: rt_robot_prediction
    image: rt_robot_prediction
    build: 
      context: ../../../
      dockerfile: ./DTsolution/DTservices/RT_robot_prediction/Dockerfile
    networks:
      - shared-communication

networks:
  shared-communication:
    external: true